### ISSUE TITLE
[ENHANCEMENT]

### ISSUE THREAD

**Issue by WasItSilent** [Azurilex/void-issues#31]
**Describe the feature/suggestion you'd like**
Accurate Client detection

**Additional context**
Munchen has client detection however it is very scuffed, it just flags based off exlpoits such as, noclip or serilization, I understand if there isn't much you can do other than this just wanted to ask. :)

**Comment by Azurilex** [comment]
This will not be implemented. This is entirely speculation based an is impossible to be done reliably. Besides that, it's extremely laggy and hurts performance because you're constantly checking player's colliders, comparing events, and rpc's. It's a pretty useless feature that doesn't work well and lags your game. Closed.
